### ISSUE TITLE
School Overview table too wide for 13-inch screen

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#489]
On my 13-inch MacBook Pro, the School Overview table is too wide for `Homeroom` to be totally seen.
<img width="1256" alt="screen shot 2016-05-15 at 9 52 29 pm" src="https://cloud.githubusercontent.com/assets/1514487/15278510/c959697a-1ae7-11e6-9585-b7f08eeb4ace.png">

So I have to scroll to get to it. I've noticed that I always forget it's there. Ofc. this is only a concern if users  experience it. Do we know how wide users' screens are, and if they've experienced this problem or not?

**Comment by alexsoble** [comment]
This is an interesting one! 

Let's ask Uri how wide his laptop screen is and if he experiences the same issue. He has a Somerville Public Schools Windows laptop. 

Another responsiveness use case is the projector — a bit narrower than a laptop but wider than a tablet view.

**Comment by alexsoble** [comment]
Fixed by @kevinrobinson in #1488! 👍

**Comment by kevinrobinson** [comment]
@alexsoble FWIW this doesn't fix this issue (or the issue in general), just for one particular bit on the profile page that was most interfering in MTSS@WH today.
